name: Deploy to ConoHa Wing

on:
  push:
    branches:
      - main  # 'main'ブランチへのプッシュ時にデプロイを実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.7.0'  # Node.jsのバージョン

      - name: Install dependencies
        run: |
          cd ./tripnavi-app
          npm install

      - name: Build the React app
        run: |
          cd ./tripnavi-app
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./tripnavi-app/.next/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./tripnavi-app/.next/

      - name: Deploy to ConoHa Wing
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.CONOHA_HOST }}
          username: ${{ secrets.CONOHA_USER }}
          port: ${{ secrets.CONOHA_PORT }}
          key: ${{ secrets.CONOHA_KEY }}
          script: |
            rm -rf ./tripnavi-app/app/*  # デプロイ先ディレクトリをクリア
            mkdir -p ./tripnavi-app/app
            scp -r ./build/* ./tripnavi-app/app/  # ビルドされたファイルを転送
            # NginxまたはApacheの再起動、または他の設定
            sudo systemctl restart nginx  # 例: Nginxを使う場合

